docs/content/_index.md, docs/content/installation/_index.md, docs/content/introduction/_index.md, docs/content/troubleshooting/_index.md, docs/content/usage/function-layers-advanced.md, docs/content/usage/function-layers.md, docs/content/usage/metadata.md, docs/content/usage/security.md, docs/content/usage/table-layers.md
- Renamed Intro page to "About pg_tileserv" -> this seems to be more meaningful
- Small text edits throughout (add punctuation marks, remove a few extra modifiers, etc)
=> Minor doc edits

layer_table.go
This PR has 2 small fixes for server errors I bumped into:
1. added default bounds (0,0,0,0) if the ST_Extent query in GetBoundsExact() returns a null value, which was causing a 500 error.  This is reproducible by using the preview or getting JSON for an empty table.  Any comments on whether returning default bounds of `[0,0,0,0]` and center `[0, 0]` is a good option (versus, say returning `null`, or doing something else if the table is empty)?
I also removed the `xmin` null check since it should be redundant if the above change makes sense.
2. added parentheses around the geometry column in the SQL template
=> Small fixes for server errors

main.go
The unit tests call functions that reference the viper config, so I moved the viper setup into `init()`.  That way the defaults will be set for `go test`.
=> Allow tests to use config defaults

layer_proc.go, layer_proc_test.go
The first commit ensures that the function layer JSON `arguments` property always contains an array (even if it's empty), which fixes a preview error for functions that don't have any arguments other than z/x/y. If there's a reason to keep using `omitempty`, I could instead adjust the preview javascript to handle when `arguments` is undefined.
The second commit is for #28 , and fixes display of default arguments with negative values.
=> Fixes for function arguments

config/pg_tileserv.toml.example, main.go
- Enhance sample configuration file to allow for multiple CORS-allowed domains 
- Sample configuration file now documents default as `CORSOrigins = [ "*" ]`, a valid TOML array unlike a naked asterisk
- Use viper.GetStringSlice so that a slice of domains are passed on to Gorilla mux.
=> More intuitive CORSOrigins configuration parameter

config/pg_tileserv.toml.example, main.go
Fixes #7.
- Add configuration parameters to allow call to `ListenAndServeTLS`
- Verified that HTTP/2 works when connecting to `pg_tileserv` in TLS mode via CaddyServer (`proxy` mode with `insecureskipverify` to the default HTTPS port 7801) and using `curl -k` .
- HTTP/2 request multiplexing should now work helping with tile delivery throughput in production setups
=> Basic HTTPS and HTTP/2 support

assets/index.html, main.go
If *UrlBase* is set in config file, the links generated in index.html are wrong. 
This PR tries to fix it.
NB: as i'm not familiar with golang, i'm not sure about the `go.sum` and `go.mod`
generated, i let these changes in a separate commit. I've used golang `1.13`
=> Fix: Use UrlBase in index.html

config/pg_tileserv.toml.example, main.go, main_test.go, util.go, util_test.go
New feature for #54 - a config option ("BasePath") to specify a base path to mount the service at.  For example, specifying `BasePath = /tiles` would result in URLs like `http://example.com/tiles/public.wells.json`. This is a requirement for us too (we've been using nginx path rewriting to work around it).
This uses the `net/url` library to ensure that user supplied paths are tacked onto the hostname properly. One issue I would point out is it *might* be possible for users to already be using a UrlBase value that `url.Parse` doesn't like (for example, `UrlBase = localhost` without the http:// on the front). If this PR needs to handle that I can make that work.
=> option to mount the service at a specified path

tile.go
Another line with the same problem as in f0dc92dc2dd7c666bd84c23f20c3774c10b46a7b. (see #27)
=> Cast to uint for shift

.cnf.makefile, Dockerfile, Makefile
My first PR #69 had issues, sorry about that.
I took some more time to work those problems out and made sure the `buildx` addition works and makes sense.
I also realized the anti-pattern of treating multi-targets as "arguments", so I removed this. Hopefully the following contribution is the right scope.
---
~Assumes that `docker buildx` has been setup on the developer's machine.~ (now a Makefile target)
**.cnf.makefile**
Defines environment variables that are important to docker and some logic to determine the cpu arch and leaves current Makefile behavior intact.
**Dockerfile**
Added build stage from `Dockerfile.alpine` so that multi-arch support is guaranteed for centos build
**Makefile**
- Adds `make install-buildx`, will follow the steps described at the official …
=> multi-arch docker image support

hugo/content/installation/_index.md
This commit adds the missing comment markup and makes the comment match similar configs in the code base, like e.g. `README.md` or `config/pg_tileserv.toml.example`. I noticed the missing hash character and missing words in the [official docs](https://access.crunchydata.com/documentation/pg_tileserv/latest/installation/) and assume this is the code that needs to be changed to fix this.
=> Docs: fix missing start of config comment in example config in installation instructions

README.md, hugo/content/installation/_index.md
1. Default config file searching paths are `./config/pg_tileserv.toml`, `/config/pg_tileserv.toml`, `/etc/pg_tileserv.toml`. They are searched  by sequence.
2. The description of the default config file are inconsistent in README and docs.
=> docs: fix config reading sequence

layer.go
Following up on #145: We'd been getting "concurrent map iteration and map write" panics at this range over `globalLayers`; and, as in #89, acquiring the mutex around this operation seems to have put an end to the errors.
=> Retain mutex while iterating over globalLayers

examples/systemd/README.md, examples/systemd/pg_tileserv.service
This is a general systemd service script for running as a Linux service.  Should work fine on all Linux systems, perhaps with some minor path changes.
=> Systemd service template and instructions

layer_table.go
To be able to broadcast data from multiple postgresql clusters, server just have to take foreign tables into account when listing postgresql readable content.
=> Add foreign tables to available layers

.github/workflows/ci.yml, .github/workflows/docker.yml
In Github actions, we see a warning of node version deprecation. it states that node v12 will not be used further, so we need to update to node 16 at least. this PR encompasses the changes of setup-go action to the newest version. It's simple and it works
=> Update setup go to latest version

.gitignore, hugo/content/examples/example-mapbox-gl-js.md
This is a tiny issue, but I figured I could get started with something easy that happened to cause a little friction earlier today.
=> Fixed a broken link in the examples page

cql/cql.go, cql/cqlparser_base_listener.go, layer.go, layer_proc.go, layer_table.go, main.go, tile.go, util.go
I am unsure if this is helpful or not; if you'd rather I didn't do this then I'll also revert the changes in my fork.  I've simply gone through `gofmt`, `go vet`, and `go lint` as a way to get myself more familiar with the code, and applied all suggestions that wouldn't be a non-trivial code edit.  Some of the exported function comments are rather redundant, but I figure that having them in makes it easier to scan the rest of `go lint`'s output for more important feedback.
=> Applied `gofmt` and most of `go lint`'s suggestions

README.md, main.go, main_test.go, util_test.go
The primary purpose of this change is to address #131 . 
It creates a simple endpoint, which only responds to `GET` requests. It responds with `200 OK` if the server up and running. By default, the endpoint is at `/health` under the `BasePath`, but you can set an alternative path for it using the `HealthEndpoint` config key or the command-line flag `-e`.
There was discussion of multiple endpoints in the issue, but I don't think I have the necessary context to decide when `startup` versus `readiness` ones should return a 200. Also, it sounds like people may want to supply multiple alternate paths; I have left that for another day.
While I was in there, I
- added some tests for functionality that @eldang added previously
- Displayed an error message on the command line when running the …
=> Configurable and very basic health check endpoint

.github/workflows/docker.yml, Makefile
This adds the architecture to the date tag, fixes the clean target which was not updated for the architecture content, and adds manifest generation and pushing to the github workflow.
=> Hlord add manifest

main.go
Currently setting `Debug = true` in the config file is ignored.
=> enable debug logging if enabled in config file

layer_table.go
Some postgresql variant distrbution such as kingbase changed the behavior of trim to compatible with oracle, which trim does not support multi-charactor set. Use rtrim for compatibility.
=> Use rtrim instead of trim
